insert into "organization" (organization_id, is_active, status, type, name, legal_name, tax_id, foreign_tax_id, license_number, radar_status, radar_type, radar_checked_at, country, city, notes, metadata, created_at, updated_at, submitted_at, approved_at, rejected_at, deactivated_at) values ('organization_01ky8qkxj0eh3a3cdjthzpv802', true, 'activated', 'platform', 'Importou Platform', 'Importou Tecnologia Ltda',          '00000000000191', null,           null,         null,     null,      null,                                 'BR', 'São Paulo', null, null, generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, null);
insert into "organization" (organization_id, is_active, status, type, name, legal_name, tax_id, foreign_tax_id, license_number, radar_status, radar_type, radar_checked_at, country, city, notes, metadata, created_at, updated_at, submitted_at, approved_at, rejected_at, deactivated_at) values ('organization_01ky8qkxj0eh3a3cdvfs52rrxm', true, 'activated', 'importer', 'Demo Importer',     'Demo Importadora Ltda',            '11222333000181', null,           null,         'active', 'limited', generate_unique_second_timestamptz(), 'BR', 'São Paulo', null, null, generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, null);
insert into "organization" (organization_id, is_active, status, type, name, legal_name, tax_id, foreign_tax_id, license_number, radar_status, radar_type, radar_checked_at, country, city, notes, metadata, created_at, updated_at, submitted_at, approved_at, rejected_at, deactivated_at) values ('organization_01ky8qkxj0eh3a3ce6tayh75pr', true, 'activated', 'exporter', 'Demo Exporter',     'Demo Export Co.',                  null,             'US-TAX-998877', null,         null,     null,      null,                                 'US', 'Miami',     null, null, generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, null);
insert into "organization" (organization_id, is_active, status, type, name, legal_name, tax_id, foreign_tax_id, license_number, radar_status, radar_type, radar_checked_at, country, city, notes, metadata, created_at, updated_at, submitted_at, approved_at, rejected_at, deactivated_at) values ('organization_01ky8qkxj0eh3a3cecxkbhn5y1', true, 'activated', 'broker',   'Demo Broker',       'Demo Despachante Aduaneiro Ltda',  '44555666000177', null,           'RFB-12345',  null,     null,      null,                                 'BR', 'Santos',    null, null, generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, null);

insert into "user" (user_id, is_active, status, password, is_blocked, blocked_reason, created_at, updated_at, activated_at, deactivated_at) values ('user_01ky8qkxj0eh3a3cen72mv6yy3', true, 'active', '$2b$10$aEz1kd6T3hjQtE8tzTUuOeyQe0z286d4idh8MdrRjUVAEywLuxlnG', false, null, generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null);
insert into "person" (person_id, is_active, status, name, cpf, birthdate, nationality, created_at, updated_at, deactivated_at, user_id) values ('person_01ky8qkxj1eh3a3cfq53mxvkb4', true, 'created', 'Admin Importou', '11122233344', '1990-01-01', 'Brazilian', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, 'user_01ky8qkxj0eh3a3cen72mv6yy3');
insert into "contact" (contact_id, is_active, status, type, parent_type, parent_id, value, created_at, updated_at, deactivated_at) values ('contact_01ky8qkxj1eh3a3cgjk13xw258', true, 'created', 'email', 'person', 'person_01ky8qkxj1eh3a3cfq53mxvkb4', 'admin@importou.com', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null);
insert into "membership" (membership_id, is_active, status, created_at, updated_at, deactivated_at, user_id, organization_id, role_id) values ('membership_01ky8qkxj1eh3a3chkjx18e1aa', true, 'created', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, 'user_01ky8qkxj0eh3a3cen72mv6yy3', 'organization_01ky8qkxj0eh3a3cdjthzpv802', 'role_01ky8qkxhweh3a3ccpqnbpbs8z');

insert into "user" (user_id, is_active, status, password, is_blocked, blocked_reason, created_at, updated_at, activated_at, deactivated_at) values ('user_01ky8qkxj1eh3a3cet2eja89b3', true, 'active', '$2b$10$aEz1kd6T3hjQtE8tzTUuOeyQe0z286d4idh8MdrRjUVAEywLuxlnG', false, null, generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null);
insert into "person" (person_id, is_active, status, name, cpf, birthdate, nationality, created_at, updated_at, deactivated_at, user_id) values ('person_01ky8qkxj1eh3a3cfy20q9r5ea', true, 'created', 'Importer Demo', '22233344455', '1988-05-10', 'Brazilian', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, 'user_01ky8qkxj1eh3a3cet2eja89b3');
insert into "contact" (contact_id, is_active, status, type, parent_type, parent_id, value, created_at, updated_at, deactivated_at) values ('contact_01ky8qkxj1eh3a3cgr7zq26teq', true, 'created', 'email', 'person', 'person_01ky8qkxj1eh3a3cfy20q9r5ea', 'importer@importou.com', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null);
insert into "membership" (membership_id, is_active, status, created_at, updated_at, deactivated_at, user_id, organization_id, role_id) values ('membership_01ky8qkxj1eh3a3chs0xjvmv1j', true, 'created', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, 'user_01ky8qkxj1eh3a3cet2eja89b3', 'organization_01ky8qkxj0eh3a3cdvfs52rrxm', 'role_01ky8qkxhzeh3a3ccw6fk3eg3b');

insert into "user" (user_id, is_active, status, password, is_blocked, blocked_reason, created_at, updated_at, activated_at, deactivated_at) values ('user_01ky8qkxj1eh3a3cf5gse9ynz6', true, 'active', '$2b$10$aEz1kd6T3hjQtE8tzTUuOeyQe0z286d4idh8MdrRjUVAEywLuxlnG', false, null, generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null);
insert into "person" (person_id, is_active, status, name, cpf, birthdate, nationality, created_at, updated_at, deactivated_at, user_id) values ('person_01ky8qkxj1eh3a3cg595t6yg7s', true, 'created', 'Exporter Demo', null, '1985-03-20', 'American', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, 'user_01ky8qkxj1eh3a3cf5gse9ynz6');
insert into "contact" (contact_id, is_active, status, type, parent_type, parent_id, value, created_at, updated_at, deactivated_at) values ('contact_01ky8qkxj1eh3a3ch1xkxb74qa', true, 'created', 'email', 'person', 'person_01ky8qkxj1eh3a3cg595t6yg7s', 'exporter@importou.com', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null);
insert into "membership" (membership_id, is_active, status, created_at, updated_at, deactivated_at, user_id, organization_id, role_id) values ('membership_01ky8qkxj1eh3a3cj24ahjcp0t', true, 'created', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, 'user_01ky8qkxj1eh3a3cf5gse9ynz6', 'organization_01ky8qkxj0eh3a3ce6tayh75pr', 'role_01ky8qkxj0eh3a3cd7h6rrnxe1');

insert into "user" (user_id, is_active, status, password, is_blocked, blocked_reason, created_at, updated_at, activated_at, deactivated_at) values ('user_01ky8qkxj1eh3a3cfen8c0g8x1', true, 'active', '$2b$10$aEz1kd6T3hjQtE8tzTUuOeyQe0z286d4idh8MdrRjUVAEywLuxlnG', false, null, generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null);
insert into "person" (person_id, is_active, status, name, cpf, birthdate, nationality, created_at, updated_at, deactivated_at, user_id) values ('person_01ky8qkxj1eh3a3cg8skwr1jmn', true, 'created', 'Broker Demo', '33344455566', '1992-07-15', 'Brazilian', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, 'user_01ky8qkxj1eh3a3cfen8c0g8x1');
insert into "contact" (contact_id, is_active, status, type, parent_type, parent_id, value, created_at, updated_at, deactivated_at) values ('contact_01ky8qkxj1eh3a3chatdgbh069', true, 'created', 'email', 'person', 'person_01ky8qkxj1eh3a3cg8skwr1jmn', 'broker@importou.com', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null);
insert into "membership" (membership_id, is_active, status, created_at, updated_at, deactivated_at, user_id, organization_id, role_id) values ('membership_01ky8qkxj1eh3a3cjax5g1medb', true, 'created', generate_unique_second_timestamptz(), generate_unique_second_timestamptz(), null, 'user_01ky8qkxj1eh3a3cfen8c0g8x1', 'organization_01ky8qkxj0eh3a3cecxkbhn5y1', 'role_01ky8qkxj0eh3a3cden9rf85gm');
